# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Parametros.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 80, 551, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 220, 541, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 180, 541, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 20, 581, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(290, 40, 20, 191))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(550, 50, 20, 181))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(310, 60, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(390, 60, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(440, 60, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(510, 60, 31, 16))
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(310, 100, 41, 21))
        self.comboBox.setToolTip("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(360, 40, 20, 191))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(420, 40, 20, 191))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(480, 40, 20, 191))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(10, 130, 541, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(500, 100, 41, 21))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(500, 150, 41, 21))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_3.setGeometry(QtCore.QRect(500, 200, 41, 21))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_4.setGeometry(QtCore.QRect(490, 250, 81, 21))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(340, 250, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(20, 290, 541, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 340, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 380, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 420, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 460, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(160, 340, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(160, 380, 62, 22))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(160, 420, 62, 22))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(160, 460, 62, 22))
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(340, 340, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(390, 340, 62, 22))
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(340, 380, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(390, 380, 62, 22))
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(310, 420, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(390, 420, 62, 22))
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(390, 460, 62, 22))
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(310, 460, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_9.setGeometry(QtCore.QRect(390, 500, 62, 22))
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(310, 500, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_10.setGeometry(QtCore.QRect(160, 500, 62, 22))
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(30, 500, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 560, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.boton_regresar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_regresar.setGeometry(QtCore.QRect(100, 560, 91, 31))
        self.boton_regresar.setObjectName("boton_regresar")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(380, 100, 41, 21))
        self.comboBox_2.setToolTip("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(440, 100, 41, 21))
        self.comboBox_3.setToolTip("")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(310, 150, 41, 21))
        self.comboBox_4.setToolTip("")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(380, 150, 41, 21))
        self.comboBox_5.setToolTip("")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(440, 150, 41, 21))
        self.comboBox_6.setToolTip("")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(310, 200, 41, 21))
        self.comboBox_7.setToolTip("")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(380, 200, 41, 21))
        self.comboBox_8.setToolTip("")
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_9.setGeometry(QtCore.QRect(440, 200, 41, 21))
        self.comboBox_9.setToolTip("")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 604, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Riesgos"))
        self.label_2.setText(_translate("MainWindow", "Riesgos Financieros y administrativos "))
        self.label_3.setText(_translate("MainWindow", "Riesgos operativos y técnicos "))
        self.label_4.setText(_translate("MainWindow", "Riesgos de niveles de servicio  y compensaciones"))
        self.label_5.setText(_translate("MainWindow", "Variabilidad "))
        self.label_6.setText(_translate("MainWindow", "Probl"))
        self.label_7.setText(_translate("MainWindow", "Peso"))
        self.label_8.setText(_translate("MainWindow", "Riesgo "))
        self.comboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox.setItemText(1, _translate("MainWindow", "10 "))
        self.comboBox.setItemText(2, _translate("MainWindow", "20 "))
        self.comboBox.setItemText(3, _translate("MainWindow", "30 "))
        self.comboBox.setItemText(4, _translate("MainWindow", "40 "))
        self.comboBox.setItemText(5, _translate("MainWindow", "50 "))
        self.comboBox.setItemText(6, _translate("MainWindow", "60 "))
        self.comboBox.setItemText(7, _translate("MainWindow", "70 "))
        self.comboBox.setItemText(8, _translate("MainWindow", "80 "))
        self.comboBox.setItemText(9, _translate("MainWindow", "90 "))
        self.comboBox.setItemText(10, _translate("MainWindow", "100 "))
        self.label_9.setText(_translate("MainWindow", "Riesgo Total Calculado"))
        self.label_10.setText(_translate("MainWindow", "Margen Personal "))
        self.label_11.setText(_translate("MainWindow", "Margen Otro Opex "))
        self.label_12.setText(_translate("MainWindow", "Margen Opex 1T"))
        self.label_13.setText(_translate("MainWindow", "Margen Capex"))
        self.label_14.setText(_translate("MainWindow", "IPC "))
        self.label_15.setText(_translate("MainWindow", "TRM "))
        self.label_16.setText(_translate("MainWindow", "Impuestos"))
        self.label_17.setText(_translate("MainWindow", "Meses Fact"))
        self.label_18.setText(_translate("MainWindow", "Impuestos"))
        self.label_19.setText(_translate("MainWindow", "% Imprevistos"))
        self.pushButton.setText(_translate("MainWindow", "Añadir "))
        self.boton_regresar.setText(_translate("MainWindow", "Regresar"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "10 "))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "20 "))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "30 "))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "40 "))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "50 "))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "60 "))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "70 "))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "80 "))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "90 "))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "100 "))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "10 "))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "20 "))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "30 "))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "40 "))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "50 "))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "60 "))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "70 "))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "80 "))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "90 "))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "100 "))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "10 "))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "20 "))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "30 "))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "40 "))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "50 "))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "60 "))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "70 "))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "80 "))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "90 "))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "100 "))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "10 "))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "20 "))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "30 "))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "40 "))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "50 "))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "60 "))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "70 "))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "80 "))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "90 "))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "100 "))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "10 "))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "20 "))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "30 "))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "40 "))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "50 "))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "60 "))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "70 "))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "80 "))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "90 "))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "100 "))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "10 "))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "20 "))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "30 "))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "40 "))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "50 "))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "60 "))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "70 "))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "80 "))
        self.comboBox_7.setItemText(9, _translate("MainWindow", "90 "))
        self.comboBox_7.setItemText(10, _translate("MainWindow", "100 "))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "10 "))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "20 "))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "30 "))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "40 "))
        self.comboBox_8.setItemText(5, _translate("MainWindow", "50 "))
        self.comboBox_8.setItemText(6, _translate("MainWindow", "60 "))
        self.comboBox_8.setItemText(7, _translate("MainWindow", "70 "))
        self.comboBox_8.setItemText(8, _translate("MainWindow", "80 "))
        self.comboBox_8.setItemText(9, _translate("MainWindow", "90 "))
        self.comboBox_8.setItemText(10, _translate("MainWindow", "100 "))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "10 "))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "20 "))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "30 "))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "40 "))
        self.comboBox_9.setItemText(5, _translate("MainWindow", "50 "))
        self.comboBox_9.setItemText(6, _translate("MainWindow", "60 "))
        self.comboBox_9.setItemText(7, _translate("MainWindow", "70 "))
        self.comboBox_9.setItemText(8, _translate("MainWindow", "80 "))
        self.comboBox_9.setItemText(9, _translate("MainWindow", "90 "))
        self.comboBox_9.setItemText(10, _translate("MainWindow", "100 "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

