# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tipooferta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 426)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boton_regresar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_regresar.setGeometry(QtCore.QRect(190, 320, 91, 31))
        self.boton_regresar.setObjectName("boton_regresar")
        self.boton_regresar_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_regresar_2.setGeometry(QtCore.QRect(50, 70, 351, 51))
        self.boton_regresar_2.setObjectName("boton_regresar_2")
        self.boton_regresar_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_regresar_3.setGeometry(QtCore.QRect(50, 160, 351, 51))
        self.boton_regresar_3.setObjectName("boton_regresar_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 444, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton_regresar.setText(_translate("MainWindow", "Regresar"))
        self.boton_regresar_2.setText(_translate("MainWindow", "Oferta para adición"))
        self.boton_regresar_3.setText(_translate("MainWindow", "Oferta para Nuevo Proyecto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
